const crosswords = [
  {
    key: 'crossword_76',
    name: 'جدول شماره ۷۶',
    rows: 7,
    columns: 7,
    questions: {
      horizontal: [
        ['زور', 'یار آفتابه'],
        ['دوستی', 'رنگ سفید مات'],
        ['شجاعت و دلیری'],
        ['کشت بارانی', 'دوست'],
        ['جنگاور'],
        ['داخل', 'از لوازم آرایش'],
        ['پیش و جلو', 'درون حاشیه']
      ],
      vertical: [
        ['پیوند دادن'],
        ['قرض و دین', 'برنج'],
        ['گلابی'],
        ['حس بویایی', 'یار مرد'],
        ['عنصر شیمیایی فلزی'],
        ['مخفف اگر', 'مزد'],
        ['ازت']
      ]
    },
    blackBlocks: [
      [false, false, false, true, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, true, false],
      [false, false, false, true, false, false, false],
      [false, true, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, true, false, false, false],
    ],
    answers:[
      ['ج', 'ب', 'ر', '', 'ل', 'گ', 'ن'],
      ['و', 'د', '', 'ش', 'ی', 'ر', 'ی'],
      ['ش', 'ه', 'ا', 'م', 'ت', '', 'ت'],
      ['', 'ی', 'م', '', 'ی', 'ا', 'ر'],
      ['', '', 'ر', 'ز', 'م', 'ج', 'و'],
      ['د', 'ر', 'و', 'ن', '', 'ر', 'ژ'],
      ['ن', 'ز', 'د', '', '', 'ت', 'ن']
    ]
  },
  {
    key: 'crossword_80',
    name: 'جدول شماره ۸۰',
    rows: 9,
    columns: 9,
    questions: {
      horizontal: [
        ['از بازیگران سیرک', 'پیش شماره'], 
				['ماسک', 'آزمایش لباس'], 
				['شخن شیوا', 'از شهرهای استان فارس'], 
				['مفصل پر کار', 'بز کوهی'], 
				['رئیس جمهور مقتول آمریکا'], 
				['حرف ندا', 'ادب آموختن'], 
				['دریایی در شمال اقیانوس آرام', 'وسیله احتیاطی'], 
				['خاکسپاری', 'حادثه و اتفاق'], 
				['هنوز فرنگی', 'عوارض قانونی'],
      ],
      vertical: [
        ['دومین شهر بزرگ عراق', 'جاویدان'],
        ['قوس قزح', 'از شهرهای استان کرمان'],
        ['طول', 'پسوند آلودگی'],
        ['صنم', 'موج گیر رادیو'],
        ['بلندترین قله قاره آمریکا'],
        ['طریقه و روش', 'فیلمی از بهرامیان'],
        ['جزئی از بدن', 'پارچه ابریشمی'],
        ['آدرس ترسیمی', 'مناجات'],
        ['فیلمی از احمدرضا درویش', 'بوی خوش'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, true, false, false],
      [false, false, false, false, false, true, false, false, false],
      [false, false, false, true, false, false, false, false, false],
      [false, true, false, false, false, false, true, false, false],
      [true, false, false, false, false, false, false, false, true],
      [false, false, true, false, false, false, false, true, false],
      [false, false, false, false, false, true, false, false, false],
      [false, false, false, true, false, false, false, false, false],
      [false, false, true, false, false, false, false, false, false],
    ],
    answers:[
      ['ب', 'ن', 'د', 'ب', 'ا', 'ز', '', 'ک', 'د'],
      ['ص', 'و', 'ر', 'ت', 'ک', '', 'پ', 'ر', 'و'],
      ['ر', 'س', 'ا', '', 'و', 'ر', 'ا', 'و', 'ی'],
      ['ه', '', 'ز', 'ا', 'ن', 'و', '', 'ک', 'ل'],
      ['', 'ج', 'ا', 'ن', 'ک', 'ن', 'د', 'ن', ''],
      ['ا', 'ی', '', 'ت', 'ا', 'د', 'ب', '', 'ن'],
      ['ب', 'ر', 'ی', 'ن', 'گ', '', 'ی', 'د', 'ک'],
      ['د', 'ف', 'ن', '', 'و', 'ا', 'ق', 'ع', 'ه'],
      ['ی', 'ت', '', 'م', 'ا', 'ل', 'ی', 'ا', 'ت'],
    ]
  },
  {
    key: 'crossword_116',
    name: 'جدول شماره ۱۱۶',
    rows: 7,
    columns: 7,
    questions: {
      horizontal: [
        ['درخت جنگلی', 'سال قبل'],
				['مجازات شرعی', 'دلربا و جلب کننده'], 
				['وارونه'], 
				['تبهکاران'], 
				['از لوازم نقاشی'], 
				['جوهر', 'زایش'], 
				['مرکب رستم', 'پرخاش'],
      ],
      vertical: [
        ['نرم دلی', 'میوه و نتیجه'],
        ['اقامه دعوی', 'گوشه نشین شطرنج'],
        ['جنگ و نزاع'],
        ['پوشاک پا'],
        ['تیمچه'],
        ['بچه دزد معروف', 'فرو ریختن'],
        ['یک چهارم', 'سرمایه پایدار'],
      ]
    },
    blackBlocks: [
      [false, false, false, true, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, true, false],
      [true, false, false, false, false, false, true],
      [false, true, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, true, false, false, false],
    ],
    answers:[
      ['ر', 'ا', 'ش', '', 'پ', 'ا', 'ر'],
      ['ح', 'د', '', 'ج', 'ا', 'ل', 'ب'],
      ['م', 'ع', 'ک', 'و', 'س', '', 'ع'],
      ['', 'ا', 'ش', 'ر', 'ا', 'ر', ''],
      ['ث', '', 'م', 'ا', 'ژ', 'ی', 'ک'],
      ['م', 'ر', 'ک', 'ب', '', 'ز', 'ا'],
      ['ر', 'خ', 'ش', '', 'ت', 'ش', 'ر'],
    ]
  },
  {
    key: 'crossword_160',
    name: 'جدول شماره ۱۶۰',
    rows: 9,
    columns: 11,
    questions: {
      horizontal: [
        ['کسی که از آینده خبر می دهد', 'آدم خشن و بی فرهنگ'],
				['بیابان و صحرا', 'شکوه و شکایت', 'ضمیر فرانسوی'],
				['سطح دست', 'خم شدن', 'پشت سر'],
				['مهمانخانه مدرن', 'ناشناخته و نامعلوم'],
				['چاشنی پرمصرف', 'کیسه صابون'],
				['بنیادی و اصولی', 'خانه  سنگ پشت'],
				['سلاح رستم', 'لبخند زدن', 'رده و رسته'],
				['بله ایتالیایی', 'پیرامون دهان چارپایان', 'دیرینه و بی آغاز'],
				['نقصان و کاستی', 'عیالوار'],
      ],
      vertical: [
        ['فشنگ خالی', 'قسمتی از تفنگ'],
        ['پیدا کردن', 'چرک زخم'],
        ['استوار ساختن', 'بدگوی'],
        ['دشواری در کار', 'شخص و فرد', 'رودی در ایتالیا'],
        ['قلیل و اندک', 'مطالعه مقدماتی'],
        ['از میوه های تابستانی'],
        ['حصار و دژ', 'بله بیگانه'],
        ['زیر پا مانده', 'افسار گسیخته', 'تار و کدر'],
        ['معلول و ناتوان', 'به دنیا آوردن'],
        ['اشتیاق و آرزومندی', 'مسافت'],
        ['وقت چیزی یا کاری', 'ضامن و متعهد'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, true, false, false, false, false, false],
      [false, false, false, false, true, false, false, false, true, false, false],
      [false, false, true, false, false, false, false, true, false, false, false],
      [false, false, false, true, false, false, false, false, false, true, false],
      [true, false, false, false, true, false, true, false, false, false, true],
      [false, true, false, false, false, false, false, true, false, false, false],
      [false, false, false, true, false, false, false, false, true, false, false],
      [false, false, true, false, false, false, true, false, false, false, false],
      [false, false, false, false, false, true, false, false, false, false, false],
    ],
    answers:[
      ['پ', 'ی', 'ش', 'گ', 'و', '', 'ق', 'ل', 'ت', 'ش', 'ن'],
      ['و', 'ا', 'د', 'ی', '', 'گ', 'ل', 'ه', '', 'و', 'و'],
      ['ک', 'ف', '', 'ر', 'ک', 'و', 'ع', '', 'ع', 'ق', 'ب'],
      ['ه', 'ت', 'ل', '', 'م', 'ج', 'ه', 'و', 'ل', '', 'ت'],
      ['', 'ن', 'م', 'گ', '', 'ه', '', 'ل', 'ی', 'ف', ''],
      ['م', '', 'ا', 'س', 'ا', 'س', 'ی', '', 'ل', 'ا', 'ک'],
      ['گ', 'ر', 'ز', '', 'ت', 'ب', 'س', 'م', '', 'ص', 'ف'],
      ['س', 'ی', '', 'پ', 'و', 'ز', '', 'ا', 'ز', 'ل', 'ی'],
      ['ک', 'م', 'ب', 'و', 'د', '', 'م', 'ت', 'ا', 'ه', 'ل'],
    ]
  },
  {
    key: 'crossword_279',
    name: 'جدول شماره ۲۷۹',
    rows: 13,
    columns: 11,
    questions: {
      horizontal: [
        ['نگهبان عالم', 'ماه'],
				['زه‌های کمان', 'صبور و بردبار'],
				['رمق آخر', 'سلاح انفجاری', 'جمع ماده'],
				['جسم انسان غیر از سر', 'باطل کردن', 'روش و شیوه'],
				['اشاره', 'به تازگی'],
				['کالا و متاع', 'آوازه'],
				['قیمت ‌بازاری', 'فعال و کاری', 'نمایش تلویزیونی'],
				['نشست', 'مایع لعابدار'],
				['نژاد مردم پرو', 'نوعی چاشنی غذا'],
				['عزا و ماتم', 'پرستار', 'سرخورده'],
				['کبوتر صحرایی', 'هزینه', 'بازی نفس‌گیر!'],
				['بزرگترین سرخرگ‌بدن', 'تن و بدن'],
				['قسمت و نصیب', 'حیوان استرالیایی'],
      ],
      vertical: [
        ['طرف و کنار', 'شخصیتی در شاهنامه'],
        ['حمایت و طرفداری', 'روزانه'],
        ['اسب آذری', 'جوان و دلیر', 'مبارز'],
        ['خالص', 'جمع مسلک', 'گذشتن بر چیزی'],
        ['فاش شده', 'اشخاص', 'تنها'],
        ['بت', 'از آفات مزرعه', 'گوشه‌نشین شطرنج'],
        ['سایه‌گاه', 'پوچ و خالی', 'زیانکاری'],
        ['اندک', 'نمونه مشت است', 'نبرد و پیکار'],
        ['سرپرستی', 'هدایت کردن', 'عدد ورزشی'],
        ['پیشکار', 'کشتزار برنج'],
        ['دستگاهی که برای خنک کردن موتورهای احتراقی مورد استفاده قرار می گیرد', 'کشتی ژاپنی'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false, true, false, false, false],
      [false, false, false, false, false, true, false, false, false, false, false],
      [false, false, true, false, false, false, true, false, false, false, false],
      [false, false, false, true, false, false, false, true, false, false, false],
      [true, false, false, false, false, true, false, false, false, false, false],
      [false, false, false, false, true, false, false, false, false, true, false],
      [false, false, true, false, false, false, false, false, true, false, false],
      [false, true, false, false, false, false, true, false, false, false, false],
      [false, false, false, false, false, true, false, false, false, false, true],
      [false, false, false, true, false, false, false, true, false, false, false],
      [false, false, false, false, true, false, false, false, true, false, false],
      [false, false, false, false, false, true, false, false, false, false, false],
      [false, false, false, true, false, false, false, false, false, false, false],
    ],
    answers:[
      ['ج', 'ه', 'ا', 'ن', 'ب', 'ا', 'ن', '', 'ق', 'م', 'ر'],
      ['ا', 'و', 'ت', 'ا', 'ر', '', 'ش', 'ک', 'ی', 'ب', 'ا'],
      ['ن', 'ا', '', 'ب', 'م', 'ب', '', 'م', 'و', 'ا', 'د'],
      ['ب', 'د', 'ن', '', 'ل', 'غ', 'و', '', 'م', 'ش', 'ی'],
      ['', 'ا', 'ی', 'م', 'ا', '', 'ا', 'خ', 'ی', 'ر', 'ا'],
      ['ا', 'ر', 'و', 'س', '', 'ش', 'ه', 'ر', 'ت', '', 'ت'],
      ['ف', 'ی', '', 'ا', 'ک', 'ت', 'ی', 'و', '', 'ش', 'و'],
      ['', '', 'ج', 'ل', 'س', 'ه', '', 'ا', 'ه', 'ا', 'ر'],
      ['', 'ی', '', 'ک', 'ا', '', 'خ', 'ر', 'د', 'ل', ''],
      ['س', 'و', 'گ', '', 'ن', 'ر', 'س', '', 'ا', 'ی', 'س'],
      ['ی', 'م', 'ا', 'م', '', 'خ', 'ر', 'ج', '', 'ز', 'و'],
      ['ا', 'ی', 'و', 'ر', 'ت', '', 'ا', 'ن', 'د', 'ا', 'م'],
      ['ب', 'ه', 'ر', '', 'ک', 'ا', 'ن', 'گ', 'و', 'ر', 'و'],
    ]
  },
  {
    key: 'crossword_309',
    name: 'جدول شماره ۳۰۹',
    rows: 11,
    columns: 7,
    questions: {
      horizontal: [
        ['موقعیت مساعد'],
				['پایتخت ونزوئلا'],
				['بخشش و کرم'],
				['عملی در کشاورزی'],
				['پوشاک سر', 'کافی'],
				['رکن اصلی نماز', 'دیدنی از رژه'],
				['نشانه مفعولی باواسطه', 'نژادی در آسیا'],
				['رئوف و بامحبت'],
				['پر کردن'],
				['شغل شوفر'],
				['دماغه ای در آفریقا'],
      ],
      vertical: [
        ['قرص روانگردان', 'جایگاه درندگان', 'علامت مفعول بی‌واسطه'],
        ['ساختمانی تاریخی در پاریس', 'رئیس جیمزباند'],
        ['از سرداران داریوش‌سوم', 'نوعی نوشیدنی'],
        ['گوشه هندسی', 'آبگیر'],
        ['بی‌نظیر و بی‌مانند', 'چیزی را روی زمین یا میز یا سطح همواری لغزاندن و به جلو راندن'],
        ['کلام تعجب بانوان', 'عمل جذب'],
        ['گرداگرد لب و دهان', 'بخشی از اوستا', 'پسندیده و خوب'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true],
      [true, false, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, true, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, false, true],
      [true, true, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
    ],
    answers:[
      ['ا', 'ک', 'ا', 'ز', 'ی', 'و', 'ن'],
      ['ک', 'ا', 'ر', 'ا', 'ک', 'ر', 'س'],
      ['س', 'خ', 'ا', 'و', 'ت', '', ''],
      ['', '', '', 'ی', 'ا', 'ر', 'ی'],
      ['ک', 'ل', 'ا', 'ه', '', 'ب', 'س'],
      ['ن', 'ی', 'ت', '', 'س', 'ا', 'ن'],
      ['ا', 'ز', '', 'ا', 'ر', 'ی', 'ا'],
      ['م', 'ه', 'ر', 'ب', 'ا', 'ن', ''],
      ['', '', 'ا', 'ک', 'ن', 'د', 'ن'],
      ['ر', 'ا', 'ن', 'ن', 'د', 'گ', 'ی'],
      ['ا', 'م', 'ی', 'د', 'ن', 'ی', 'ک'],
    ]
  },
  {
    key: 'crossword_317',
    name: 'جدول شماره ۳۱۷',
    rows: 15,
    columns: 7,
    questions: {
      horizontal: [
        ['کنیه مبارک امام علی(ع)'],
				['بانی‌سلسله قراقویونلو'],
				['شهر صنعتی آلمان', 'نوعی نی که در آب می روید'],
				['ترکیب رنگ آبی با قرمز', 'حرف ندا'],
				['حمله بردن'],
				['خوش سیما'],
				['نام ترکی', 'پیامبرخوش سیما'],
				['سم موجود در سیگار'],
				['از شهدای صدر اسلام', 'جدید و تازه'],
				['دلواپس و مضطرب'],
				['رشته‌کوهی در آسیای مرکزی'],
				['وتر کمان', 'ژاپن قدیم'],
				['پرنده ای از نوع مرغابی', 'قطعه الکترونیکی'],
				['شهری در استان خراسان شمالی'],
				['خسته‌کننده و دردناک'],
      ],
      vertical: [
        ['نزدیکتر', 'باز دارنده', 'زوج ها'],
        ['خارج', 'سفره چرمین', 'دومین شهر بزرگ فلات تبت'],
        ['له شده', 'فیلسوف آلمانی', 'لباس آخرت'],
        ['موضوع و زمینه', 'جشن ایرانیان قدیم در چهارم شهریور', 'طاقچه بالا'],
        ['میز قرآن خوانی', 'برادری', 'سالوس و مزور'],
        ['جمع موج', 'صحرای مصر', 'سرپرست یک‌شرکت'],
        ['تومورى که درمان آن بسیار سخت باشد', 'تکنیک‌ها', 'الهه عقل و هنر'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, true, false, false, false],
      [false, false, false, false, true, false, false],
      [true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true],
      [false, false, true, false, false, false, false],
      [false, false, false, true, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
    ],
    answers:[
      ['ا', 'ب', 'و', 'ج', 'ع', 'ف', 'ر'],
      ['ق', 'ر', 'ا', 'م', 'ح', 'م', 'د'],
      ['ر', 'و', 'ر', '', '', '', ''],
      ['ب', 'ن', 'ف', 'ش', '', '', ''],
      ['', '', 'ت', 'ه', 'ا', 'ج', 'م'],
      ['م', 'ا', 'ه', 'ر', 'خ', '', ''],
      ['ا', 'د', '', 'ی', 'و', 'س', 'ف'],
      ['ن', 'ی', 'ک', 'و', 'ت', 'ی', 'ن'],
      ['ع', 'م', 'ا', 'ر', '', 'ن', 'و'],
      ['', '', 'ن', 'گ', 'ر', 'ا', 'ن'],
      ['ا', 'ل', 'ت', 'ا', 'ی', '', ''],
      ['ز', 'ه', '', 'ن', 'ا', 'ر', 'ا'],
      ['و', 'ا', 'ک', '', 'ک', 'ی', 'ت'],
      ['ا', 'س', 'ف', 'ر', 'ا', 'ی', 'ن'],
      ['ج', 'ا', 'ن', 'ف', 'ر', 'س', 'ا'],
    ]
  },
  {
    key: 'crossword_319',
    name: 'جدول شماره ۳۱۹',
    rows: 10,
    columns: 8,
    questions: {
      horizontal: [
        ['نیرو گرفتن پس از بیماری'],
				['نماینده حقوقی', 'در دست نقاش ‌است'],
				['گاهی با بارش گم می‌شود!', 'گل گندم'],
				['کلام تنفر', 'ریشخند'],
				['ضربه‌ای در بوکس'],
				['زبانه کشیدن آتش'],
				['فعال و کاری', 'یک خودمانی'],
				['خشكاد است و خشكي بزرگ در جغرافيا', 'از رنگ‌های اصلی'],
				['سنگ انداختن', 'يخرفت'],
				['دارای مقام و مرتبه عالی'],
      ],
      vertical: [
        ['در حال جوشیدن', 'نزدیکتر'],
        ['بسنده کردن', 'بی عیب و نقص'],
        ['بسیار درخشان', 'ملکه روسیه در سده هجدهم'],
        ['مخلوط آب و خاک', 'اداره دارایی قدیم'],
        ['کشوری آفریقایی', 'نقشه انگلیسی'],
        ['به فروش رسیده', 'نغمه و بانگ'],
        ['بیزاری', 'شبه‌جزیره‌ای در غرب اروپا'],
        ['ملاحظه', 'بهترین وضع'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false, false],
      [false, false, false, false, true , false, false, false],
      [false, false, false, true , false, false, false, false],
      [false, false, true , false, false, false, false, false],
      [false, false, false, false, false, false, true , true ],
      [true , true , false, false, false, false, false, false],
      [false, false, false, false, false, true , false, false],
      [false, false, false, false, true , false, false, false],
      [false, false, false, true , false, false, false, false],
      [false, false, false, false, false, false, false, false],
    ],
    answers:[
      ['ج', 'ا', 'ن', 'گ', '', '', 'ت', 'ن'],
      ['و', 'ک', 'ی', 'ل', '', 'ر', 'ن', 'گ'],
      ['ش', 'ت', 'ر', '', 'ل', 'و', 'ف', 'ا'],
      ['ا', 'ف', '', 'م', 'س', 'خ', 'ر', 'ه'],
      ['ن', 'ا', 'ک', 'ا', 'و', 'ت', '', ''],
      ['', '', 'ا', 'ل', 'ت', 'ه', 'ا', 'ب'],
      ['ا', 'ک', 'ت', 'ی', 'و', '', 'ی', 'ه'],
      ['ق', 'ا', 'ر', 'ه', '', 'ا', 'ب', 'ی'],
      ['ر', 'م', 'ی', '', 'م', 'و', 'ر', 'ن'],
      ['ب', 'ل', 'ن', 'د', 'پ', 'ا', 'ی', 'ه'],
    ]
  },
  {
    key: 'crossword_410',
    name: 'جدول شماره ۴۱۰',
    rows: 11,
    columns: 7,
    questions: {
      horizontal: [
        ['شاکر'],
				['بی دین و ملحد', 'از نت‌های موسیقی'],
				['روی سالاد می‌ریزند', 'نیکوتر'],
				['طرز لباس پوشیدن', 'رنج و ناخوشی'],
				['واحد پول نیجریه'],
				['معادل فارسی چیلر'],
				['بخشش از مال و جان خویش'],
				['پیام آسمانی', 'چهره و رخسار'],
				['مؤسس سلسله اشکانی', 'از اعضای تنفسی'],
				['از چاشنی‌های غذا', 'وسیله بازی تنیس'],
				['مجازاً تریلی'],
      ],
      vertical: [
        ['خرد کردن', 'بخش اساسی سازنده ماده'],
        ['گلر سابق رئال‌مادرید', 'آفتاب پرست'],
        ['طاقچه بالا', 'کاستن'],
        ['بنده و غلام', 'رفوزگی', 'بزرگترین جزیره یونان'],
        ['بیشترین حد', 'حرف ندا'],
        ['تاج و دیهیم', 'کشتی جنگی شکاری'],
        ['طرد شده', 'واحدسنجش زلزله'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, true, false, false, false],
      [false, false, false, false, false, true, false],
      [true, false, false, false, false, false, true],
      [false, true, false, false, false, false, false],
      [false, false, false, true, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, false, false],
    ],
    answers: [
      ['ش', '', 'ر', 'گ', '', 'ا', 'ر'],
      ['ک', 'ا', 'ف', 'ر', '', 'ف', 'ا'],
      ['س', 'س', '', 'ا', 'ح', 'س', 'ن'],
      ['ت', 'ی', 'پ', '', 'د', 'ر', 'د'],
      ['ن', 'ا', 'ی', 'ر', 'ا', '', 'ه'],
      ['', 'س', 'ر', 'د', 'ک', 'ن', ''],
      ['ک', '', 'ا', 'ش', 'ب', 'ا', 'ر'],
      ['و', 'ح', 'ی', '', 'ر', 'و', 'ی'],
      ['ا', 'ر', 'ش', 'ک', '', 'ش', 'ش'],
      ['ر', 'ب', '', 'ر', 'ا', 'ک', 'ت'],
      ['ک', 'ا', 'ن', 'ت', 'ی', 'ن', 'ر'],
    ],
  },
  {
    key: 'crossword_444',
    name: 'جدول شماره ۴۴۴',
    rows: 15,
    columns: 7,
    questions: {
      horizontal: [
        ['حق دلالی کاری'],
				['نازل تر', 'علامت مفعولی'],
				['یاری', 'از درختان جنگلی'],
				['از گل‌های خوشبو'],
				['بانگ قمری', 'سرود و نغمه'],
				['پاندول ساعت', 'گرداگرد لب و دهان'],
				['امدادرسانی'],
				['شهری در آلمان', 'بخشنده'],
				['ملون'],
				['پسوند حاصل‌مصدر', 'خدمتکار پیر'],
				['ایالتی در ونزوئلا', 'از چاشنی‌های غذا'],
				['چهره ای زیبا دارد'],
				['اسب چاپار', 'واحدی در علم‌ فیزیک'],
				['چهارمن تبریزی', 'جایگاه'],
				['پدیده وارونگی هوا'],
      ],
      vertical: [
        ['رسیدن به آرزو', 'باغبان'],
        ['پسوند دارندگی', 'قدرت و نیرو', 'جرأت و توان داشتن'],
        ['کیک معروف', 'رشته پهن', 'چرک زخم'],
        ['بیماری خطرناک', 'جرقه آتش', 'فقیر و بی‌چیز', 'زینت رو'],
        ['بند و طناب', 'ورزش ‌ذهنی', 'در سالاد می‌ریزند'],
        ['از شهرهای استان تهران', 'اژدهای افسانه ای یونان باستان', 'نوعی آینه یا عدسی'],
        ['غریبه', 'بدین جهت و بدین سبب'],
      ]
    },
    blackBlocks: [
      [false, false, false, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, true, false, false, false],
      [false, true, false, false, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, false, false, true, true],
      [false, false, false, true, false, false, false],
      [true, true, false, false, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, true, false, false],
      [false, false, false, false, false, true, false],
      [false, false, false, true, false, false, false],
      [false, false, true, false, false, false, false],
      [false, false, false, false, false, false, false],
    ],
    answers: [
      ['ک', 'م', 'ی', 'س', 'ی', 'و', 'ن'],
      ['ا', 'ن', 'ز', 'ل', '', 'ر', 'ا'],
      ['م', 'د', 'د', '', 'ر', 'ا', 'ش'],
      ['ر', '', 'ی', 'ا', 'س', 'م', 'ن'],
      ['و', 'ت', '', 'خ', 'ن', 'ی', 'ا'],
      ['ا', 'و', 'ن', 'گ', '', 'ن', 'س'],
      ['ی', 'ا', 'و', 'ر', 'ی', '', ''],
      ['ی', 'ن', 'ا', '', 'و', 'ه', 'ب'],
      ['', '', 'ر', 'ن', 'گ', 'ی', 'ن'],
      ['گ', 'ی', '', 'د', 'ا', 'د', 'ا'],
      ['ل', 'ا', 'ر', 'ا', '', 'ر', 'ب'],
      ['پ', 'ر', 'ی', 'ر', 'خ', '', 'ر'],
      ['ی', 'ا', 'م', '', 'ی', 'ک', 'ا'],
      ['ر', 'ی', '', 'م', 'ا', 'و', 'ی'],
      ['', 'ی', '', 'و', '', 'ژ', 'ن'],
    ],
  },
  // {
  //   key: 'crossword_56',
  //   name: 'جدول شماره ۵۶',
  //   rows: 9,
  //   columns: 9,
  //   questions: {
  //     horizontal: [
  //       ['جنس و متاع', 'جمع ادیب'],
  //       ['سایبان چشم', 'سالم و بی عیب'],
  //       ['پوستین', 'حامله و آبستن'],
  //       ['سرخرگ', 'مادر آذری'],
  //       ['ظاهر و هویدا'],
  //       ['آلونک', 'پریشان خاطر و آشفته'],
  //       ['مساوات', 'جام جمشید'],
  //       ['قاره پهناور', 'دیکته'],
  //       ['بشارت دهنده', 'از وسایل پرواز'],
  //     ],
  //     vertical: [
  //       ['تفحص و جستجو', 'گوشت بریان روی آتش'],
  //       ['ناقص و ناتمام', 'سوال'],
  //       ['از اقوام ایرانی', 'توانایی و طاقت'],
  //       ['فرومایگان', 'محموله'],
  //       ['حاشا نمودن'],
  //       ['بردگی', 'در مَثَل به نوبت است'],
  //       ['تسلیت و دلگرمی', 'من و شما'],
  //       ['شرح و تعبیر', 'باشکوه و عظیم'],
  //       ['فرماندهان', 'مقابل همین'],
  //     ]
  //   },
  //   blackBlocks: [
  //     [false, false, false, false, true, false, false, false, false],
  //     [false, false, false, false, true, false, false, false, false],
  //     [false, false, true, false, false, false, false, false, false],
  //     [false, false, false, false, false, true, false, false, false],
  //     [true, true, false, false, false, false, false, true, true],
  //     [false, false, false, true, false, false, false, false, false],
  //     [false, false, false, false, false, false, true, false, false],
  //     [false, false, false, false, true, false, false, false, false],
  //     [false, false, false, false, true, false, false, false, false],
  //   ],
  //   answers:[
  //     ['ک', 'ا', 'ل', 'ا', '', '', 'د', 'ب', 'ا'],
  //     ['ا', 'ب', 'ر', '', '', 'س', 'ل', 'ی', 'م'],
  //     ['و', 'ت', '', '', 'ا', '', 'گ', 'ا', 'ر'],
  //     ['ش', 'ر', 'ی', 'ا', 'ن', '', 'ر', 'ن', 'ا'],
  //     ['', '', '', '', 'ک', 'ا', 'م', '', ''],
  //     ['ک', 'پ', 'ر', '', 'ا', 'س', 'ی', 'م', 'ا'],
  //     ['ب', 'ر', '', 'ب', 'ر', 'ی', '', 'ج', 'ل'],
  //     ['ا', 'س', 'ی', 'ا', '', 'ا', 'م', 'ل', 'ا'],
  //     ['ب', 'ش', 'ی', 'ر', '', 'ب', 'ا', 'ل', 'ن'],
  //   ]
  // }, // TODO remove 82.60%
  // {
  //   key: 'crossword_187',
  //   name: 'جدول شماره ۱۸۷',
  //   rows: 9,
  //   columns: 11,
  //   questions: {
  //     horizontal: [
  //       ['آدرس ترسیمی', 'هجران و فراق'],
  //       ['ایمن و مصون', 'واحد فروش گردو', 'اشاره به شخص غایب'],
  //       ['ویتامین نور خورشید', 'نسبت زن و شوهر به یکدیگر', 'آسمان'],
  //       ['از درختان جنگلی بلند', 'عمودی'],
  //       ['لون و فام', 'بهشت و پردیس'],
  //       ['دستگاه شمارش انداز برای برق', 'چارپای باربر'],
  //       ['شانه و کتف', 'مسرت و نشاط', 'بیماری و مرض'],
  //       ['چاشنی غذا', 'مهمانخانه مدرن', 'کج و مایل'],
  //       ['اولاد پیامبر(ص)', 'پرستشگاه یهودیان'],
  //     ],
  //     vertical: [
  //       ['چارچوب', 'نشانی'],
  //       ['چوپان', 'بیماری مسری و عفونی'],
  //       ['گشوده و باز', 'از ابزار باغبانی'],
  //       ['حشره چسبنده', 'شکم بند طبی', 'نشانه جمع'],
  //       ['فلز الکتریکی', 'پراکندگی'],
  //       ['جشنواره'],
  //       ['وسیله رفت و روب', 'از رفته به جا مانده'],
  //       ['سرای محبت', 'رشته خیاطی', 'خیر و برکت'],
  //       ['محصول سینما', 'تصدیق فرانسوی'],
  //       ['موی گردن اسب', 'دادگر و داور'],
  //       ['درختچه آپارتمانی', 'التماس و تضرع'],
  //     ]
  //   },
  //   blackBlocks: [
  //     [false, false, false, false, false, true, false, false, false, false, false],
  //     [false, false, false, false, true, false, false, false, true, false, false],
  //     [false, false, true, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, false, true, false],
  //     [true, false, false, false, true, false, true, false, false, false, true],
  //     [false, true, false, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, true, false, false],
  //     [false, false, true, false, false, false, true, false, false, false, false],
  //     [false, false, false, false, false, true, false, false, false, false, false],
  //   ],
  //   answers:[
  //     ['ک', 'ر', 'و', 'ک', 'ی', '', 'ج', 'د', '', 'ی', 'ی'],
  //     ['ا', 'م', 'ا', 'ن', '', 'ف', 'ا', 'ل', '', 'ا', 'و'],
  //     ['', '', '', 'ه', '', 'س', 'ر', '', 'ف', 'ل', 'ک'],
  //     ['', '', '', '', '', 'ت', 'و', 'ن', 'ی', '', 'ا'],
  //     ['', 'ر', 'ن', 'گ', '', 'ی', '', 'خ', 'ل', 'د', ''],
  //     ['ا', '', '', 'ن', '', 'و', 'ر', '', 'م', '', 'ز'],
  //     ['د', 'و', 'ش', '', 'ش', 'ا', 'د', 'ی', '', 'د', 'ا'],
  //     ['ر', 'ب', '', 'ه', 'ت', 'ل', '', 'م', '', '', 'ر'],
  //     ['س', 'ا', 'د', 'ا', 'ت', '', '', 'ن', '', '', 'ی'],
  //   ]
  // }, // TODO remove 76.54%
  // {
  //   key: 'crossword_234',
  //   name: 'جدول شماره ۲۳۴',
  //   rows: 9,
  //   columns: 11,
  //   questions: {
  //     horizontal: [
  //       ['درجات', 'برنامه تلویزیونی پی دار'],
  //       ['فراوان', 'غذای مریض', 'نت سوم'],
  //       ['بنده زر خرید', 'نهایی', 'نیرومند و پر زور'],
  //       ['از صور فلکی', 'دست کم'],
  //       ['فریاد عدالت', 'پارسایی'],
  //       ['مشایعت', 'نابینا'],
  //       ['نوعی یقه', 'صفت گربه', 'آب بند'],
  //       ['خبر افشاگرانه', 'پرده نقاشی', 'از جنس مو'],
  //       ['کودک پر تحرک', 'اندوهگین و غمگین'],
  //     ],
  //     vertical: [
  //       ['آن که مرده و مالی از او باقی مانده باشد', 'از توابع سقز'],
  //       ['خم بزرگ', 'شهر صنعتی آلمان'],
  //       ['کلام تنفر', 'گل همیشه بهار'],
  //       ['اسب سرخ تیره', 'حیوان وحشی', 'اطراف لب و دهان'],
  //       ['خاندان و دودمان', 'ترسان و گریزان'],
  //       ['از تکنیک های نقاشی'],
  //       ['پروتئین گیاهی', 'خدای درویش'],
  //       ['سبکی در موسیقی', 'دختر آذری', 'عنوان شغل'],
  //       ['محله ای در تهران', 'سرخود و بی بند و بار'],
  //       ['رودی در ترکمنستان', 'پرونده'],
  //       ['پست فطرت', 'رده و رسته'],
  //     ]
  //   },
  //   blackBlocks: [
  //     [false, false, false, false, false, true, false, false, false, false, false],
  //     [false, false, false, false, true, false, false, false, true, false, false],
  //     [false, false, true, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, false, true, false],
  //     [true, false, false, false, true, false, true, false, false, false, true],
  //     [false, true, false, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, true, false, false],
  //     [false, false, true, false, false, false, true, false, false, false, false],
  //     [false, false, false, false, false, true, false, false, false, false, false],
  //   ],
  //   answers:[
  //     ['', 'ک', '', 'ت', '', '', 'س', 'ر', '', 'ا', 'ل'],
  //     ['', 'و', '', 'ر', '', 'س', 'و', 'پ', '', 'م', 'ی'],
  //     ['', 'ا', '', 'غ', 'ا', 'ی', 'ی', '', 'ق', 'و', 'ی'],
  //     ['', 'ف', 'ر', '', 'ل', 'ا', 'ا', 'ق', 'ل', '', 'م'],
  //     ['', 'ر', 'ا', 'د', '', 'ه', '', 'ز', 'ه', 'د', ''],
  //     ['', '', 'ب', 'د', 'ر', 'ق', 'ه', '', 'ک', 'و', 'ر'],
  //     ['ا', 'ر', 'و', '', 'م', 'ل', 'و', 'س', '', 'س', 'د'],
  //     ['ل', 'و', '', 'ب', 'و', 'م', '', 'م', '', 'ی', ''],
  //     ['ت', 'ر', 'ع', 'ر', 'ع', '', '', 'ت', '', 'ه', ''],
  //   ]
  // }, // TODO remove 71.60%
  // {
  //   key: 'crossword_247',
  //   name: 'جدول شماره ۲۴۷',
  //   rows: 11,
  //   columns: 11,
  //   questions: {
  //     horizontal: [
  //       ['اصرار کردن', 'غم و اندوه'],
  //       ['نوعی زراعت', 'کارگردان فیلم بمانی'],
  //       ['عدد خیطی', 'یازده', 'سرانجام و عاقبت'],
  //       ['از یاد بردن', 'مثل و مانند'],
  //       ['نامی دخترانه', 'آشکار و نمایان', 'تخم مرغ فرنگی'],
  //       ['ضمیر فرانسوی', 'ماه پرتابی', 'خط کش مهندسی'],
  //       ['زیبارو', 'از شهرهای فرانسه', 'کارگر کشتی'],
  //       ['در نوردیدن', 'ساز چنگ'],
  //       ['دوره ها و زمان ها', 'نبض گرفتن', 'چوب خوشبو'],
  //       ['خفته و غنود', 'جانشین'],
  //       ['فریاد', 'سرخس نر'],
  //     ],
  //     vertical: [
  //       ['بازار سرپوشیده', 'وسیله سنگ اندازی'],
  //       ['ایل و طایفه', 'بندگی', 'خودروی کره ای'],
  //       ['قیمت بازاری', 'سلام تلفنی', 'گرد چیزی گشتن'],
  //       ['مادر آذری', 'برگشتن و باز آمدن'],
  //       ['ورم و پف', 'ضمیر داخلی', 'سنگریزه'],
  //       ['راه میانبر', 'نوعی گیوه', 'ماه سرد'],
  //       ['چین و چروک پوست', 'طایفه ایرانی', 'جاهلتر'],
  //       ['خیلی سریع', 'زنگ و درای'],
  //       ['رودی در جمهوری آذربایجان', 'نوعی جامه زنانه', 'حرف تعجب'],
  //       ['نخ تابیده', 'زمین آماده کشت', 'فتح و پیرزوی'],
  //       ['مات', 'نوعی دستگاه نمایش'],
  //     ]
  //   },
  //   blackBlocks: [
  //     [false, false, false, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, false, false, false],
  //     [false, false, true, false, false, true, false, false, false, false, false],
  //     [false, true, false, false, false, false, true, false, false, true, false],
  //     [false, false, false, false, true, false, false, false, true, false, false],
  //     [true, false, false, true, false, false, false, true, false, false, true],
  //     [false, false, true, false, false, false, true, false, false, false, false],
  //     [false, true, false, false, true, false, false, false, false, true, false],
  //     [false, false, false, false, false, true, false, false, true, false, false],
  //     [false, false, false, false, false, false, false, true, false, false, false],
  //     [false, false, false, true, false, false, false, false, false, false, false],
  //   ],
  //   answers:[
  //     ['د', '', 'ف', '', 'ا', 'ر', 'ی', '', 'ک', 'ر', 'ح'],
  //     ['ا', 'ب', 'ی', '', 'م', 'ه', 'ر', 'ج', 'و', 'ی', 'ی'],
  //     ['ل', '', '', 'ا', 'ا', '', 'ا', 'خ', 'ر', 'س', 'ر'],
  //     ['ا', '', 'ا', 'ن', 'س', 'ا', '', 'ت', 'ا', '', 'ا'],
  //     ['ن', 'ی', 'ل', 'ا', '', 'ج', 'ل', 'ی', '', 'ا', 'ن'],
  //     ['', 'و', 'و', '', 'ت', 'ی', 'ر', '', 'ت', 'ی', ''],
  //     ['ف', 'غ', '', 'ا', 'و', 'ت', '', 'ج', 'ا', 'ش', 'و'],
  //     ['ل', '', 'ط', 'ی', '', 'ه', 'ا', 'ر', 'پ', '', 'ی'],
  //     ['ا', 'ز', 'م', 'ا', 'ن', '', 'ا', 'س', '', 'ظ', 'د'],
  //     ['خ', 'و', 'ا', 'ب', 'ی', 'د', 'ه', '', 'و', 'ف', 'ی'],
  //     ['ن', 'د', 'ا', '', 'ک', 'ی', 'ر', 'د', 'ا', 'ر', 'و'],
  //   ]
  // }, // TODO remove 79.79%
];

export default crosswords;
